# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=255)),
                ('short', models.CharField(max_length=5)),
                ('version', models.CharField(max_length=5)),
                ('fields', models.TextField(null=True)),
            ],
        ),
    ]
