# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 18:14
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yatse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tickets_reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_record', models.BooleanField(default=True)),
                ('c_date', models.DateTimeField(default=datetime.datetime.now)),
                ('u_date', models.DateTimeField(default=datetime.datetime.now)),
                ('d_date', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('search', models.TextField()),
                ('c_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('d_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('u_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
