#!/bin/bash

#set -e

if [ "$1" = "configure" ] ; then
	echo "mod package: configureing"

	sites=`python -c "from distutils.sysconfig import get_python_lib; print get_python_lib()"`

    ln -s /usr/share/yatse/site-packages/yatse $sites 2>/dev/null
    ln -s /usr/share/yatse/site-packages/bootstrap_toolkit $sites 2>/dev/null
fi

exit 0
