#!/bin/bash

#set -e

if [ "$1" = "upgrade" ] ; then
    echo "mod package: upgrading"
    rm -r /usr/share/yatse/site-packages/yatse 2>/dev/null
    rm -r /usr/share/yatse/site-packages/bootstrap_toolkit 2>/dev/null
fi

exit 0
